name: flutter_neat_and_clean_calendar
description: Simple and clean flutter calendar with ability to slide up/down to
  show weekly/monthly calendar. Forked from
  [flutter_clean_calender](https://pub.dev/packages/flutter_clean_calendar)
version: 0.1.2+4
homepage: https://github.com/rwbr/flutter_neat_and_clean_calendar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  date_utils: ^0.1.0+3
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
